import Link from "next/link";
import { Eye, FileText } from "lucide-react";
import type { DocumentFileType } from "@/documents/config";
import { DOCUMENT_FILE_TYPE_LABELS, formatDocumentSize } from "@/documents/config";
import { DocumentDeleteAction } from "@/components/documents/document-delete-action";
import { Button } from "@/components/ui/button";

type DocumentStatus = "UPLOADING" | "UPLOADED" | "PROCESSING" | "COMPLETED" | "FAILED" | "CANCELLED" | "ARCHIVED" | "PROCESSED";
const STATUS: Record<DocumentStatus, string> = { UPLOADING: "Uploading", UPLOADED: "Uploaded", PROCESSING: "Processing", COMPLETED: "Completed", FAILED: "Failed", CANCELLED: "Cancelled", ARCHIVED: "Archived", PROCESSED: "Completed" };

export function DocumentsTable({ companyId, documents }: { companyId: string; documents: Array<{ id: string; originalFileName: string; fileType: DocumentFileType; fileSize: bigint; documentStatus: DocumentStatus; uploadedBy: { name: string }; createdAt: Date }> }) {
  return <div className="overflow-x-auto rounded-lg border border-ink-100 bg-white shadow-card"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-ink-100 bg-surface-muted text-xs uppercase tracking-wide text-ink-500"><tr>{["Filename", "Type", "Size", "Uploaded By", "Uploaded At", "Status", "Actions"].map((h) => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-ink-100">{documents.map((d) => <tr key={d.id} className="hover:bg-surface-subtle"><td className="max-w-xs px-4 py-3"><div className="flex items-center gap-2"><FileText className="h-4 w-4 shrink-0 text-ink-400" /><span className="truncate font-medium text-ink-800" title={d.originalFileName}>{d.originalFileName}</span></div></td><td className="px-4 py-3 text-ink-600">{DOCUMENT_FILE_TYPE_LABELS[d.fileType]}</td><td className="px-4 py-3 text-ink-600">{formatDocumentSize(d.fileSize)}</td><td className="px-4 py-3 text-ink-600">{d.uploadedBy.name}</td><td className="whitespace-nowrap px-4 py-3 text-ink-600">{d.createdAt.toLocaleString()}</td><td className="px-4 py-3"><span className="inline-flex rounded-full border border-ink-200 bg-surface-muted px-2 py-1 text-xs font-medium text-ink-700">{STATUS[d.documentStatus]}</span></td><td className="px-4 py-3"><div className="flex items-center justify-end gap-1"><Link href={`/companies/${companyId}/documents/${d.id}`}><Button type="button" variant="ghost" size="icon" aria-label={`View details for ${d.originalFileName}`}><Eye className="h-4 w-4" /></Button></Link><DocumentDeleteAction companyId={companyId} documentId={d.id} fileName={d.originalFileName} /></div></td></tr>)}</tbody></table></div>;
}
