import Link from "next/link";
import { Eye, FileText } from "lucide-react";
import type { DocumentFileType } from "@/documents/config";
import { DOCUMENT_FILE_TYPE_LABELS, formatDocumentSize } from "@/documents/config";
import { DocumentDeleteAction } from "@/components/documents/document-delete-action";
import { Button } from "@/components/ui/button";
import { DocumentRetryAction } from "@/components/documents/document-retry-action";

type DocumentStatus = "UPLOADED" | "PROCESSING" | "PROCESSED" | "FAILED" | "ARCHIVED";
const STATUS: Record<DocumentStatus, string> = { UPLOADED: "Uploaded", PROCESSING: "Processing", PROCESSED: "Processed", FAILED: "Failed", ARCHIVED: "Archived" };

export function DocumentsTable({ companyId, documents }: { companyId: string; documents: Array<{
  id: string; originalFileName: string; fileType: DocumentFileType; fileSize: bigint; documentStatus: DocumentStatus; uploadedBy: { name: string }; createdAt: Date;
  processingResult: { pageCount: number | null; sheetCount: number | null; rowCount: number | null; columnCount: number | null; requiresOcr: boolean; processingError: string | null; processedAt: Date | null } | null;
}> }) {
  return <div className="overflow-x-auto rounded-lg border border-ink-100 bg-white shadow-card"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b border-ink-100 bg-surface-muted text-xs uppercase tracking-wide text-ink-500"><tr>{["File Name", "Type", "Size", "Status", "Processing", "Uploaded By", "Uploaded Date", "Actions"].map(h => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-ink-100">{documents.map(d => <tr key={d.id} className="hover:bg-surface-subtle"><td className="max-w-xs px-4 py-3"><div className="flex items-center gap-2"><FileText className="h-4 w-4 shrink-0 text-ink-400"/><span className="truncate font-medium text-ink-800" title={d.originalFileName}>{d.originalFileName}</span></div></td><td className="px-4 py-3 text-ink-600">{DOCUMENT_FILE_TYPE_LABELS[d.fileType]}</td><td className="px-4 py-3 text-ink-600">{formatDocumentSize(d.fileSize)}</td><td className="px-4 py-3"><span className="inline-flex rounded-full border border-ink-200 bg-surface-muted px-2 py-1 text-xs font-medium text-ink-700">{STATUS[d.documentStatus]}</span></td><td className="px-4 py-3 text-xs text-ink-600"><div>{d.processingResult?.pageCount != null ? `${d.processingResult.pageCount} pages` : null}{d.processingResult?.sheetCount != null ? `${d.processingResult.pageCount != null ? " · " : ""}${d.processingResult.sheetCount} sheets` : null}{d.processingResult?.rowCount != null ? `${d.processingResult.pageCount != null || d.processingResult.sheetCount != null ? " · " : ""}${d.processingResult.rowCount} rows` : null}</div>{d.processingResult?.requiresOcr ? <div className="mt-1 text-pending">OCR needed later</div> : null}{d.processingResult?.processingError ? <div className="mt-1 text-negative">Processing failed</div> : null}</td><td className="px-4 py-3 text-ink-600">{d.uploadedBy.name}</td><td className="whitespace-nowrap px-4 py-3 text-ink-600">{d.createdAt.toLocaleString()}</td><td className="px-4 py-3"><div className="flex items-center justify-end gap-1"><Link href={`/companies/${companyId}/documents/${d.id}`}><Button type="button" variant="ghost" size="icon" aria-label={`View ${d.originalFileName}`} title="View"><Eye className="h-4 w-4"/></Button></Link>{d.documentStatus === "FAILED" ? <DocumentRetryAction companyId={companyId} documentId={d.id}/> : null}<DocumentDeleteAction companyId={companyId} documentId={d.id} fileName={d.originalFileName}/></div></td></tr>)}</tbody></table></div>;
}
