function PreviewTable({ columns, rows }: { columns: string[]; rows: unknown[][] }) {
  if (!columns.length && !rows.length) return <p className="text-sm text-ink-500">No extracted tabular data was found.</p>;
  const width = Math.max(columns.length, ...rows.map((r) => r.length), 0);
  const headers = Array.from({ length: width }, (_, i) => columns[i] || `Column ${i + 1}`);
  return <div className="overflow-x-auto rounded border border-ink-100"><table className="min-w-full text-xs"><thead className="bg-surface-muted"><tr>{headers.map((h, i) => <th key={i} className="whitespace-nowrap px-3 py-2 text-left font-medium text-ink-600">{String(h)}</th>)}</tr></thead><tbody className="divide-y divide-ink-100">{rows.map((row, r) => <tr key={r}>{headers.map((_, i) => <td key={i} className="max-w-xs whitespace-nowrap px-3 py-2 text-ink-700">{String(row[i] ?? "")}</td>)}</tr>)}</tbody></table></div>;
}

export function ExtractedDataPreview({ preview }: { preview: any }) {
  if (!preview) return null;
  return <section className="rounded-lg border border-ink-100 bg-white p-4 shadow-card"><div className="mb-3"><h2 className="font-display text-sm font-semibold text-ink-900">Extracted data</h2><p className="mt-1 text-xs text-ink-500">Read-only preview of structured extraction. The original source remains unchanged.</p></div>{preview.kind === "csv" ? <PreviewTable columns={preview.columns} rows={preview.rows}/> : null}{preview.kind === "excel" ? <div className="space-y-4">{preview.sheets.map((sheet: any) => <div key={sheet.name}><p className="mb-2 text-xs font-semibold text-ink-700">Sheet: {sheet.name}</p><PreviewTable columns={sheet.columns} rows={sheet.rows}/></div>)}</div> : null}{preview.kind === "pdf" ? <div className="space-y-3">{preview.pages.map((page: any) => <div key={page.pageNumber} className="rounded border border-ink-100 bg-surface-subtle p-3"><p className="mb-2 text-xs font-semibold text-ink-700">Page: {page.pageNumber}</p><pre className="whitespace-pre-wrap break-words text-xs leading-5 text-ink-700">{page.text.join("\n") || "No readable text on this page."}</pre></div>)}</div> : null}{preview.kind === "image" ? <p className="rounded border border-pending/20 bg-pending/5 px-3 py-2 text-sm text-ink-700">This image is prepared for future OCR. No text was inferred in this phase.</p> : null}</section>;
}
